export { default as HomePage } from "./HomePage";
export { default as LoggedIn } from "./AuthPages/LoggedIn";
export { default as NotFound } from "./NotFound";
export { default as Dashboard } from "./Dashboard";
export { default as LoginPage } from "./AuthPages/LoginPage";
export { default as RegisterPage } from "./AuthPages/RegisterPage";
export { default as CalendarPage } from "./CalendarPage";
export { default as ProfilePage } from "./Profile";
export { default as AppointmentPage } from "./Appointment";
